name: practical
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  retry: ^3.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  flutter_svg: ^2.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
    - family: Pattaya
      fonts:
        - asset: fonts/Pattaya-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/src/localization/arb/
  output_dir: lib/src/localization/generated/
  use_deferred_loading: true